//
// Created by jedsaxon on 8/10/23.
//

#include <string>
#include "Hasher.h"

/// Converts a char[] into a hash
unsigned int Hasher::Hash(void *key, int length) {
    // Declare a pointer to an unsigned char and cast the key to that type
    unsigned char *p = static_cast<unsigned char *>(key);

    // Initialize the hash value to 0x811c9dc5
    unsigned int h = 0x811c9dc5;

    // Loop through each character in the key
    for (int i = 0; i < length; i++) {
        // XOR the hash value with the current character and multiply by 0x01000193
        h = (h ^ p[i]) * 0x01000193;
    }

    // Return the hash value
    return h;
}

/// Uses the hash generated by Hasher::Hash, limiting the hash by the amount of keys inside the hash table
unsigned int Hasher::StringToHash(std::string const &key, unsigned int maxKeys) {
    // Get the C-style string representation of the key
    char const* p = &key[0];

    // Generate a hash using Hasher::Hash
    unsigned int index = Hash((void *) p, key.size());

    // Limit the hash value by the number of keys in the hash table
    return index % maxKeys;
}

